# Generated by Django 3.2.4 on 2021-06-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='address1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='address2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='zipcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
